{
 "title": "Covid Dashboard",
 "time": { "from": "2020-03-21T07:39:20.704Z", "to": "2020-07-27T18:30:00.000Z" },
 "templating": {
  "list": [
   { "name": "States", "query": "select state from state_data" },
   {
    "name": "County",
    "label": "County Name",
    "query": "select distinct county_name from county_data"
   },
   { "name": "StateData", "label": "Pick one State ", "query": "select state from state_data" },
   {
    "name": "MonthNumber",
    "label": "Select Month",
    "query": "SELECT distinct EXTRACT(MONTH FROM date) from county_data"
   }
  ]
 },
 "panels": [
  {
   "title": "Covid Deaths",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  state_name AS metric,\n  deaths\nFROM county_data\nWHERE\n  $__timeFilter(date)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Deaths in US Counties",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  county_name AS metric,\n  deaths\nFROM county_data\nWHERE\n  $__timeFilter(date) AND\n  county_name IN ($County)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Covid Cases",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  state AS metric,\n  sum(cases) AS \"cases\"\nFROM state_data\nWHERE\n  $__timeFilter(date) AND\n  state IN ($States)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Total Covid Deaths in US",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  state AS metric,\n  deaths\nFROM state_data\nWHERE\n  date = '2020-07-28'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Total Covid Cases in US",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  state AS metric,\n  cases\nFROM state_data\nWHERE\n  date = '2020-07-28'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Deaths in Selected State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  state AS metric,\n  deaths\nFROM state_data\nWHERE\n  $__timeFilter(date) AND\n  state = '$StateData'\n  AND Extract(MONTH from date) = '$MonthNumber'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Cases in Selected State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  state AS metric,\n  cases\nFROM state_data\nWHERE\n  $__timeFilter(date) AND\n  state = '$StateData'\n  AND Extract(MONTH from date) = '$MonthNumber'\nORDER BY 1,2"
    }
   ]
  }
 ]
}